import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { Readable } from "node:stream";

import { NextResponse } from "next/server";

import { verifyAdminSession } from "../../../../../../../lib/admin-auth";
import { getFulfilmentItem } from "../../../../../../../lib/fulfilment-items";
import { findLocalPrintFile } from "../../../../../../../lib/print-output-files";
import { generateWebImageFromMaster } from "../../../../../../../lib/web-image-generation";

export const runtime = "nodejs";

const PREVIEW_MAX_EDGE = 1600;
const PREVIEW_QUALITY = 82;

type RouteContext = {
  params: Promise<{ order_item_id: string }>;
};

const previewCachePath = (filePath: string, modifiedMs: number): string => {
  const key = createHash("sha1").update(`${filePath}:${modifiedMs}`).digest("hex");
  return path.join(os.tmpdir(), "exhibition-print-previews", `${key}.jpg`);
};

export async function GET(request: Request, context: RouteContext) {
  const isAuthed = await verifyAdminSession(request);
  if (!isAuthed) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { order_item_id } = await context.params;
  const item = await getFulfilmentItem(order_item_id);
  if (!item) {
    return NextResponse.json({ error: "Fulfilment item not found." }, { status: 404 });
  }

  const local = await findLocalPrintFile(item);
  if (!local) {
    return NextResponse.json(
      {
        error:
          "Prepared print file not found under LOCAL_OUTPUT_DIR (print-output). It is generated by the fulfilment worker — not the master TIFF.",
      },
      { status: 404 },
    );
  }

  const filePath = local.path;
  let fileStat: Awaited<ReturnType<typeof fs.stat>>;
  try {
    fileStat = await fs.stat(filePath);
    if (!fileStat.isFile()) {
      return NextResponse.json({ error: "Prepared print file is missing." }, { status: 404 });
    }
  } catch {
    return NextResponse.json({ error: "Prepared print file is missing on disk." }, { status: 404 });
  }

  const filename = local.name;
  const mode = new URL(request.url).searchParams.get("mode") === "preview" ? "preview" : "download";

  if (mode === "preview") {
    try {
      const cachePath = previewCachePath(filePath, fileStat.mtimeMs);
      await fs.mkdir(path.dirname(cachePath), { recursive: true });

      let needsGenerate = true;
      try {
        const cacheStat = await fs.stat(cachePath);
        needsGenerate = cacheStat.mtimeMs < fileStat.mtimeMs || cacheStat.size === 0;
      } catch {
        needsGenerate = true;
      }

      if (needsGenerate) {
        await generateWebImageFromMaster(filePath, cachePath, {
          maxEdge: PREVIEW_MAX_EDGE,
          quality: PREVIEW_QUALITY,
          timeoutMs: 180_000,
        });
      }

      const jpeg = await fs.readFile(cachePath);
      return new NextResponse(jpeg, {
        status: 200,
        headers: {
          "Content-Type": "image/jpeg",
          "Cache-Control": "private, max-age=120",
          "Content-Length": String(jpeg.byteLength),
        },
      });
    } catch (error) {
      console.error("Print file preview failed", error);
      return NextResponse.json(
        {
          error:
            error instanceof Error
              ? error.message
              : "Failed to generate a preview from the prepared print TIFF.",
        },
        { status: 500 },
      );
    }
  }

  const stream = createReadStream(filePath);
  return new NextResponse(Readable.toWeb(stream) as ReadableStream, {
    status: 200,
    headers: {
      "Content-Type": "image/tiff",
      "Content-Disposition": `attachment; filename="${filename.replace(/"/g, "")}"`,
      "Content-Length": String(fileStat.size),
      "Cache-Control": "private, no-store",
    },
  });
}
