#!/bin/bash
set -e

APP_ROOT="$HOME/apps/exhibition"

echo "→ Pulling latest code"
# next-env.d.ts is regenerated by Next on build; discard local drift so pull never blocks
git checkout -- next-env.d.ts 2>/dev/null || true
git pull --ff-only

echo "→ Backing up uploaded media"
mkdir -p "$APP_ROOT/uploads-backup/images" "$APP_ROOT/uploads-backup/video"
if [ -d "public/images" ]; then
  cp -r public/images/. "$APP_ROOT/uploads-backup/images/"
fi
if [ -d "public/video" ]; then
  cp -r public/video/. "$APP_ROOT/uploads-backup/video/"
fi

echo "→ Installing dependencies"
npm ci

echo "→ Installing worker dependencies"
python3 -m venv .worker-venv
.worker-venv/bin/pip install -r worker/requirements.txt

echo "→ Building Next.js"
npm run build

echo "→ Ensuring media directories"
mkdir -p public/images public/video storage/icc logs
if [ -n "${WEB_MEDIA_DIR:-}" ]; then
  mkdir -p "$WEB_MEDIA_DIR/images" "$WEB_MEDIA_DIR/video"
fi

# Preserve uploaded media in the canonical location
if [ -d "$APP_ROOT/uploads-backup/images" ]; then
  cp -r "$APP_ROOT/uploads-backup/images/." public/images/
fi
if [ -d "$APP_ROOT/uploads-backup/video" ]; then
  cp -r "$APP_ROOT/uploads-backup/video/." public/video/
fi

echo "→ Restarting PM2"
pm2 reload ecosystem.config.js --update-env

echo "✓ Deployed to production"
